### ISSUE TITLE
Correct local installation instructions

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/Watai#130]
After a `npm install watai`, the `go` file is not present in the `/node_modules/watai/` directory. It probably has to do with the `package.json•files` property but I'm not used to JS packaging.

**Comment by davidbgk** [comment]
I confirm that once the file is created and `chmod +x`ed the `--installed` check returns the encouraging message :)

**Comment by MattiSG** [comment]
Did you follow the “local install” procedure?

**Comment by davidbgk** [comment]
Yes, [that one](https://github.com/MattiSG/Watai#local-install).

**Comment by MattiSG** [comment]
Then I think the problem is simply that the doc is not up-to-date and dates from the time before NPM symlinked the binaries to `.bin` (or at least, before I knew it did). The solution is to update the README so that the suggested alias is `node_modules/.bin/watai`.

**Comment by davidbgk** [comment]
Agreed, `watai` executable is present in my `.bin` folder.

**Comment by MattiSG** [comment]
Fixed in 2d0f48f164ecaaca85f5d60bcb8ecbe897d6c5eb
