### ISSUE TITLE
Randomness in submitted data?

### ISSUE THREAD

**Issue by davidbgk** [MattiSG/Watai#133]
Is there a way to introduce some (pseudo)randomness in submitted data? Having the ability to submit natively a given string + hash would be nice for repeated tests without deletion, is there any example out there?

**Comment by davidbgk** [comment]
Here is what I did naively:
```
name = "Test dataset " + Math.random().toString(36).substring(7)
```

**Comment by MattiSG** [comment]
Yes, that's exactly how you're expected to do it.
Then again, don't hesitate to create `RandomData.js` that would provide helpers to other data files  :)

Just to rephrase and be sure I understood: would it help if Watai provided a “standard library” of patterns? This was also considered for checkboxes assertions, for example.

**Comment by davidbgk** [comment]
Yes, I think a couple of helpers would definitely be useful for beginners :)

**Comment by MattiSG** [comment]
Thanks for your feedback  :)

Closing this issue, feel free to ask for reopening if the answer did not solve your problem.
